from enum import StrEnum


# Brazilian electric energy market submercados
class Submarket(StrEnum):
    SOUTH = "S"
    SOUTHEAST = "SE"
    NORTHEAST = "NE"
    NORTH = "N"


class MigrationStatus(StrEnum):
    CREATED = "CRIADA"
    COMPLETED = "CONCLUIDA"
    REJECTED = "REPROVADA"
    CLOSED = "ENCERRADA"
    CANCELLED = "CANCELADA"
    EXPIRED = "EXPIRADA"


class ChangeRequestType(StrEnum):
    """Types of "solicitacoes" (troca de representante, retorno ao cativo, suspensao de
    fornecimento) accepted by the CCEE API."""

    RETURN_TO_CAPTIVE_TERMINATION = "ALTERACAO_RETORNO_CATIVO_RESILICAO"
    RETURN_TO_CAPTIVE_RESOLUTION = "ALTERACAO_RETORNO_CATIVO_RESOLUCAO"
    RETURN_TO_CAPTIVE_DISCONNECTION = "ALTERACAO_RETORNO_CATIVO_DESLIGAMENTO"
    REPRESENTATIVE_CHANGE_TERMINATION = "ALTERACAO_ALFA_VAREJISTA_RESILICAO"
    REPRESENTATIVE_CHANGE_RESOLUTION = "ALTERACAO_ALFA_VAREJISTA_RESOLUCAO"
    REPRESENTATIVE_CHANGE_DISCONNECTION = "ALTERACAO_ALFA_VAREJISTA_DESLIGAMENTO"
    SUPPLY_SUSPENSION_TERMINATION = "SUSPENSAO_FORNECIMENTO_RESILICAO"
    SUPPLY_SUSPENSION_RESOLUTION = "SUSPENSAO_FORNECIMENTO_RESOLUCAO"
    SUPPLY_SUSPENSION_DISCONNECTION = "SUSPENSAO_FORNECIMENTO_DESLIGAMENTO"
    SUPPLY_SUSPENSION_UTILITY_RESOLUTION = "SUSPENSAO_FORNECIMENTO_RESOLUCAO_UC_CONCESSIONARIA"


class ChangeRequestStatus(StrEnum):
    CREATED = "CRIADA"
    COMPLETED = "CONCLUIDA"
    REJECTED = "REPROVADA"
    CANCELLED = "CANCELADA"
    EXPIRED = "EXPIRADA"
